application: lekez200567
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: api.application
# Static files
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /partials
  static_dir: static/partials
  
  
# applications
- url: /admin/?.*
  script: views.admin.application
  login: admin
- url: /files/.*
  script: views.blobdownload.application
- url: /.*
  script: main.application

  
builtins:
- remote_api: on  
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0